export { default as Navbar } from './Navbar'
export { default as Blogs } from './Blogs'
export { default as Banner } from './Banner'
export { default as BlogPage } from './BlogPage'
export { default as Footer } from './Footer'