import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const blackOpsOne = localFont({
  src: "./assets/fonts/BlackOpsOne.ttf",
  variable: "--font-black-ops-one"
});

const gluten = localFont({
  src: "./assets/fonts/gluten.ttf",
  variable: "--font-gluten"
});

const inter = localFont({
  src: './assets/fonts/inter.ttf',
  variable: '--font-inter',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${blackOpsOne.variable} ${gluten.variable} antialiased max-w-screen-2xl mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
